/**
 * DUNK-O-METER 9000 - Biscuit & Beverage Scientific Database
 * Authentic specimens, physical coefficients, and hilarious conclusions.
 */

const BISCUIT_DATABASE = [
  {
    id: "parle-g",
    name: "Parle-G",
    tagline: "The Nation's Glucose Fuel",
    classification: "Tea Veteran",
    density: 65,
    thickness: 4.2, // mm
    crispiness: 72,
    absorptionRate: 1.35, // very thirsty
    structuralStrength: 46,
    creamFactor: 0,
    breakResistance: 40,
    shape: "rectangle",
    color: "#d49746",
    details: "Parle-G stamped monogram with fluted border",
    lore: "Legendary tea companion. Absorbs chai at near supersonic speeds. 2 seconds is bravery; 4 seconds is madness.",
    svgType: "parle-g"
  },
  {
    id: "bourbon",
    name: "Bourbon",
    tagline: "Sugar-Crusted Chocolate Fortress",
    classification: "Cream Reinforced",
    density: 82,
    thickness: 9.5,
    crispiness: 80,
    absorptionRate: 0.72,
    structuralStrength: 75,
    creamFactor: 65,
    breakResistance: 78,
    shape: "sandwich-rect",
    color: "#542c16",
    details: "Perforated top biscuit with chocolate cream sandwich & sugar crystals",
    lore: "The central chocolate cream layer acts as a hydraulic shock absorber against boiling beverages.",
    svgType: "bourbon"
  },
  {
    id: "dark-fantasy",
    name: "Dark Fantasy",
    tagline: "Molten Center Heavy Armor",
    classification: "Molten Core Fortress",
    density: 92,
    thickness: 12.0,
    crispiness: 65,
    absorptionRate: 0.55,
    structuralStrength: 86,
    creamFactor: 90,
    breakResistance: 88,
    shape: "circle",
    color: "#381a0e",
    details: "Thick cocoa shell with liquid molten chocolate interior",
    lore: "Near military-grade thermal resistance. The molten core remains unbothered by mere mortal tea.",
    svgType: "dark-fantasy"
  },
  {
    id: "milk-bikis",
    name: "Milk Bikis",
    tagline: "Lactose-Bonded Floral Matrix",
    classification: "Lactose Fortified",
    density: 74,
    thickness: 5.5,
    crispiness: 76,
    absorptionRate: 0.88,
    structuralStrength: 66,
    creamFactor: 0,
    breakResistance: 62,
    shape: "circle-fluted",
    color: "#e2aa58",
    details: "Embossed floral bottle motif with edge ridges",
    lore: "Fortified with the promise of calcium and nostalgic resilience. Holds up surprisingly well.",
    svgType: "milk-bikis"
  },
  {
    id: "good-day",
    name: "Good Day",
    tagline: "Curved Smile of Butter & Nuts",
    classification: "Cashew Reinforced",
    density: 78,
    thickness: 6.8,
    crispiness: 70,
    absorptionRate: 0.82,
    structuralStrength: 60,
    creamFactor: 15,
    breakResistance: 58,
    shape: "circle-smile",
    color: "#e8b464",
    details: "Distinct smile pattern ridges with embedded cashew specks",
    lore: "Rich in butter fats which repel initial liquid contact, but cracks easily along the smile fault lines.",
    svgType: "good-day"
  },
  {
    id: "marie-gold",
    name: "Marie Gold",
    tagline: "Thin Disc of Extreme Peril",
    classification: "Structural Liability",
    density: 50,
    thickness: 3.4,
    crispiness: 84,
    absorptionRate: 1.48,
    structuralStrength: 32,
    creamFactor: 0,
    breakResistance: 28,
    shape: "circle-marie",
    color: "#e9be75",
    details: "Delicate outer ring of puncture vents and classical wheat wreath",
    lore: "Possesses a survival half-life of 1.8 seconds. If you blink, you have donated your biscuit to the mug.",
    svgType: "marie-gold"
  },
  {
    id: "hide-seek",
    name: "Hide & Seek",
    tagline: "Choco-Chip Stress Concentrators",
    classification: "Choco-Matrix Asset",
    density: 76,
    thickness: 4.8,
    crispiness: 82,
    absorptionRate: 0.95,
    structuralStrength: 54,
    creamFactor: 20,
    breakResistance: 52,
    shape: "rect-chips",
    color: "#6b3e1f",
    details: "Dark chocolate rectangle studded with dark chocolate chips",
    lore: "Each chocolate chip serves as a micro-dam, though thermal hot spots around the chips can cause sudden cleavage.",
    svgType: "hide-seek"
  },
  {
    id: "jim-jam",
    name: "Jim Jam",
    tagline: "Viscous Jam-Glued Dual Disc",
    classification: "Jam-Glued Monolith",
    density: 85,
    thickness: 10.2,
    crispiness: 68,
    absorptionRate: 0.65,
    structuralStrength: 72,
    creamFactor: 70,
    breakResistance: 76,
    shape: "jimjam",
    color: "#f0b86a",
    details: "Vanilla biscuit sandwich with red central raspberry gummy drop & vanilla cream",
    lore: "The central jam nucleus binds the two biscuit tectonic plates through surface tension and sugary glue.",
    svgType: "jim-jam"
  },
  {
    id: "fifty-fifty",
    name: "50-50",
    tagline: "Sweet & Salty Quantum Duality",
    classification: "Bipolar Crumbler",
    density: 58,
    thickness: 3.2,
    crispiness: 90,
    absorptionRate: 1.25,
    structuralStrength: 42,
    creamFactor: 0,
    breakResistance: 38,
    shape: "rect-thin",
    color: "#e5b364",
    details: "Ultra-thin rectangular cracker perforated with dozens of micro-holes",
    lore: "Perforations act as express water slides. Half sweet, half salty, 100% prone to sudden submersion.",
    svgType: "fifty-fifty"
  },
  {
    id: "little-hearts",
    name: "Little Hearts",
    tagline: "Sugar-Glazed Cardiovascular Wonder",
    classification: "Fragile Romantic",
    density: 62,
    thickness: 7.0,
    crispiness: 88,
    absorptionRate: 1.10,
    structuralStrength: 44,
    creamFactor: 0,
    breakResistance: 40,
    shape: "heart",
    color: "#e8ab56",
    details: "Heart-shaped layered puff pastry coated in glistening caramel crystals",
    lore: "Puff pastry air pockets drink tea like a sponge. Emotional resilience: low. Thermodynamic charm: maximum.",
    svgType: "little-hearts"
  },
  {
    id: "oreo",
    name: "Oreo",
    tagline: "The Black Monolith of Dunking",
    classification: "Hydrophobic Titan",
    density: 90,
    thickness: 9.0,
    crispiness: 85,
    absorptionRate: 0.50,
    structuralStrength: 88,
    creamFactor: 80,
    breakResistance: 91,
    shape: "oreo",
    color: "#221a17",
    details: "High-contrast dark cocoa embossed discs with vanilla cream core",
    lore: "Engineered by planetary food scientists specifically to withstand liquid milk bombardment without collapsing.",
    svgType: "oreo"
  },
  {
    id: "cream-treat",
    name: "Cream Treat",
    tagline: "Double Sandwich Barrier",
    classification: "Double Barrier Defense",
    density: 79,
    thickness: 8.8,
    crispiness: 74,
    absorptionRate: 0.70,
    structuralStrength: 68,
    creamFactor: 75,
    breakResistance: 70,
    shape: "circle-cream",
    color: "#dca052",
    details: "Dual textured biscuits with strawberry/vanilla cream filling",
    lore: "Cream layer forms a hydrophobic barricade preventing radial tea diffusion.",
    svgType: "cream-treat"
  },
  {
    id: "nice",
    name: "Nice",
    tagline: "Coconut Sugar-Armor Cracker",
    classification: "Sugar Shield Crumbler",
    density: 64,
    thickness: 4.0,
    crispiness: 83,
    absorptionRate: 1.15,
    structuralStrength: 45,
    creamFactor: 0,
    breakResistance: 42,
    shape: "rect-nice",
    color: "#ddaa5e",
    details: "Rectangular with NICE debossed lettering and large surface sugar granules",
    lore: "Sugar crystals provide false optimism. Once tea dissolves the top sucrose crust, collapse is immediate.",
    svgType: "nice"
  },
  {
    id: "nutrichoice",
    name: "NutriChoice",
    tagline: "High Fiber Structural Reinforcement",
    classification: "Fibrous Resistance",
    density: 84,
    thickness: 6.2,
    crispiness: 72,
    absorptionRate: 0.76,
    structuralStrength: 76,
    creamFactor: 0,
    breakResistance: 74,
    shape: "circle-fiber",
    color: "#a4733e",
    details: "Dense wheat bran particles and coarse oat grain texture",
    lore: "Dietary fiber bonds act like rebar inside concrete. Endures long dunks through sheer fibrous stubbornness.",
    svgType: "nutrichoice"
  },
  {
    id: "monaco",
    name: "Monaco",
    tagline: "Rapid Solvation Risk",
    classification: "Immediate Dissolution Risk",
    density: 46,
    thickness: 3.0,
    crispiness: 94,
    absorptionRate: 1.65,
    structuralStrength: 26,
    creamFactor: 0,
    breakResistance: 22,
    shape: "circle-monaco",
    color: "#f1c26b",
    details: "Salt crystals on fluted golden cracker disc",
    lore: "Salt accelerates liquid osmosis. Submerging Monaco into tea is a recognized war crime in biscuit physics.",
    svgType: "monaco"
  },
  {
    id: "happy-happy",
    name: "Happy Happy",
    tagline: "Choco-Sprinkled Mood Elevator",
    classification: "Dopamine Crumbler",
    density: 70,
    thickness: 4.8,
    crispiness: 78,
    absorptionRate: 0.98,
    structuralStrength: 52,
    creamFactor: 10,
    breakResistance: 50,
    shape: "circle-happy",
    color: "#5e321b",
    details: "Chocolate cookie disc dusted with rainbow chocolate droplets",
    lore: "Provides immense psychological comfort right until the lower half separates into the murky depths.",
    svgType: "happy-happy"
  },
  {
    id: "tiger",
    name: "Tiger",
    tagline: "Ferocious Tenacity Glucose Disc",
    classification: "Ferocious Tenacity",
    density: 73,
    thickness: 4.5,
    crispiness: 77,
    absorptionRate: 1.05,
    structuralStrength: 64,
    creamFactor: 0,
    breakResistance: 60,
    shape: "rect-tiger",
    color: "#df9e44",
    details: "Embossed roaring tiger silhouette and glucose grid",
    lore: "Fights the liquid tension with feline fury. Survives longer than expected through pure aggressive glucose.",
    svgType: "tiger"
  },
  {
    id: "krackjack",
    name: "KrackJack",
    tagline: "The Original Sweet-Salty Dilemma",
    classification: "Duality Hazard",
    density: 61,
    thickness: 3.6,
    crispiness: 89,
    absorptionRate: 1.18,
    structuralStrength: 47,
    creamFactor: 0,
    breakResistance: 44,
    shape: "rect-fluted",
    color: "#e8af5c",
    details: "Scalloped wavy rectangular perimeter with pinhole vent grid",
    lore: "Balanced between sweetness and sodium, but hopelessly susceptible to hydrostatic breakdown.",
    svgType: "krackjack"
  },
  {
    id: "custom",
    name: "Custom Biscuit",
    tagline: "Unidentified Laboratory Specimen",
    classification: "Unknown Biscuit Technology",
    density: 70,
    thickness: 5.0,
    crispiness: 75,
    absorptionRate: 1.00,
    structuralStrength: 55,
    creamFactor: 30,
    breakResistance: 55,
    shape: "hexagon-tech",
    color: "#00f0ff",
    details: "User-defined structural attributes and experimental telemetry",
    lore: "A rogue biscuit concocted in unauthorized laboratory conditions.",
    svgType: "custom"
  }
];

const BEVERAGE_DATABASE = [
  {
    id: "tea",
    name: "Hot Chai (Tea)",
    icon: "☕",
    absorptionMultiplier: 1.18,
    tempEffect: "hot",
    liquidColor: "rgba(180, 83, 9, 0.9)",
    surfaceColor: "#b45309",
    liquidGlow: "rgba(245, 158, 11, 0.4)",
    bubbles: true,
    steam: true,
    viscosity: 1.0,
    description: "Boiling masala chai. Highly aggressive on biscuit cellulose."
  },
  {
    id: "coffee",
    name: "Filter Coffee",
    icon: "☕",
    absorptionMultiplier: 1.22,
    tempEffect: "hot",
    liquidColor: "rgba(68, 32, 14, 0.94)",
    surfaceColor: "#451a03",
    liquidGlow: "rgba(180, 83, 9, 0.3)",
    bubbles: true,
    steam: true,
    viscosity: 1.05,
    description: "Dark, caffeinated solvent. Acidic attack accelerates crumb detachment."
  },
  {
    id: "milk",
    name: "Warm Milk",
    icon: "🥛",
    absorptionMultiplier: 0.90,
    tempEffect: "normal",
    liquidColor: "rgba(248, 250, 252, 0.96)",
    surfaceColor: "#f1f5f9",
    liquidGlow: "rgba(255, 255, 255, 0.5)",
    bubbles: false,
    steam: true,
    viscosity: 1.25,
    description: "Lactose and lipid coating buffers the biscuit against instant decay."
  },
  {
    id: "hot-chocolate",
    name: "Hot Chocolate",
    icon: "🍫",
    absorptionMultiplier: 1.05,
    tempEffect: "hot",
    liquidColor: "rgba(58, 24, 12, 0.95)",
    surfaceColor: "#381708",
    liquidGlow: "rgba(120, 53, 15, 0.4)",
    bubbles: false,
    steam: true,
    viscosity: 1.45,
    description: "Viscous cocoa magma. Dense resistance slows penetration slightly."
  },
  {
    id: "cold-milk",
    name: "Cold Milk",
    icon: "❄️",
    absorptionMultiplier: 0.74,
    tempEffect: "cold",
    liquidColor: "rgba(224, 242, 254, 0.92)",
    surfaceColor: "#e0f2fe",
    liquidGlow: "rgba(56, 189, 248, 0.4)",
    bubbles: false,
    steam: false,
    viscosity: 1.30,
    description: "Chilled lipid suspension. The biscuit's best statistical survival chance."
  },
  {
    id: "water",
    name: "Pure Water (H2O)",
    icon: "💧",
    absorptionMultiplier: 1.32,
    tempEffect: "normal",
    liquidColor: "rgba(14, 165, 233, 0.7)",
    surfaceColor: "#38bdf8",
    liquidGlow: "rgba(14, 165, 233, 0.5)",
    bubbles: true,
    steam: false,
    viscosity: 0.95,
    description: "Universal polar solvent. Dissolves sugar bonds with merciless efficiency."
  },
  {
    id: "custom-drink",
    name: "Custom Liquid",
    icon: "🧪",
    absorptionMultiplier: 1.10,
    tempEffect: "normal",
    liquidColor: "rgba(168, 85, 247, 0.85)",
    surfaceColor: "#c084fc",
    liquidGlow: "rgba(168, 85, 247, 0.6)",
    bubbles: true,
    steam: true,
    viscosity: 1.15,
    description: "Experimental radioactive lab solution. May cause molecular anomaly."
  }
];

const ANALYSIS_MESSAGES = [
  "SCANNING BISCUIT MOLECULES...",
  "MEASURING CRUMB DENSITY & POROSITY...",
  "CALCULATING HYDROSTATIC TEA PENETRATION...",
  "ANALYZING STRUCTURAL INTEGRITY VECTORS...",
  "CHECKING CREAM REINFORCEMENT INTEGRITY...",
  "CONSULTING INTERNATIONAL BISCUIT DATABASE...",
  "QUESTIONING ALL HUMAN LIFE CHOICES...",
  "APPLYING COMPLETELY UNNECESSARY QUANTUM MATHEMATICS...",
  "SIMULATING CATASTROPHIC CRUMB COLLAPSE...",
  "CONSULTING TASTE BUD DISASTER HOTLINE...",
  "COMPUTING CRUNCH DEPRECIATION CURVE...",
  "PREPARING EXTREMELY IMPORTANT SCIENTIFIC RESULTS..."
];

const SCIENTIFIC_CONCLUSIONS = {
  champion: [ // 80 - 100%
    "This biscuit fears no beverage. It could survive re-entry into Earth's atmosphere.",
    "Remarkable structural resilience! The biscuit has established diplomatic dominance over the cup.",
    "Zero crumb casualties reported. A golden standard of snacking engineering.",
    "The biscuit emerged with crispiness intact and dignity uncompromised.",
    "Laboratory sensors report pristine structural matrix. Give this biscuit a promotion."
  ],
  skilled: [ // 60 - 79%
    "A respectable performance in dangerous liquid conditions. Proceed to consume before entropy wins.",
    "Minor sogginess detected at the lower perimeter, but the biscuit stands firm.",
    "Optimal dunk achieved: maximum flavor absorption with zero catastrophic failures.",
    "Scientific verdict: The dunk was audacious, yet tactically successful.",
    "Crispiness reduced to 48%, but structural spine remains loyal to the snacker."
  ],
  danger: [ // 40 - 59%
    "Proceed with extreme snacking caution! Structural integrity is leaving the chat.",
    "The biscuit is currently experiencing an existential crisis between solid and semi-solid.",
    "🚨 REMOVE THE BISCUIT NOW! Crumb migration has initiated.",
    "Warning: Capillary action is winning. Eat it right this second.",
    "The lower hemisphere has made peace with its destiny. Salvage immediately!"
  ],
  critical: [ // 15 - 39%
    "Structural collapse is highly probable! The biscuit is now 73% tea.",
    "Catastrophic fault line active. One sneeze and it belongs to the cup forever.",
    "Our scientists recommend immediate suction. The spoon protocol is standing by.",
    "Somewhere, a British person felt a severe cosmic disturbance in the tea.",
    "The biscuit's lawyer has filed an emergency injunction to halt all dunking."
  ],
  destroyed: [ // 0 - 14%
    "Congratulations. You have successfully invented biscuit soup.",
    "Biscuit completely destroyed. The cup has swallowed another victim.",
    "Total structural dissolution. The tea has defeated its opponent.",
    "NASA has declined to comment on this snacking tragedy.",
    "Please contact the Department of Biscuit Emergencies. There are no survivors."
  ],
  biscuitSpecific: {
    "parle-g": "Parle-G fought with patriotic bravery, but chai remains undefeated.",
    "bourbon": "The chocolate cream sandwich acted as a hero, but the outer plates surrendered.",
    "dark-fantasy": "Dark Fantasy's molten core proved too dense for standard tea physics.",
    "marie-gold": "Marie Gold disintegrated in seconds, shocking absolutely nobody in the lab.",
    "oreo": "Oreo stood steadfast, laughing at the milky abyss like an immortal cookie.",
    "little-hearts": "The little heart was broken. Again.",
    "monaco": "Monaco achieved speedrun dissolution. Academic grant well spent.",
    "fifty-fifty": "50-50 could not decide whether to dissolve sweet or salty, so it dissolved completely.",
    "jim-jam": "The raspberry jam hub remains stranded at the bottom of your cup like an ancient artifact."
  }
};
